name: Elixir CI

on:
  push:
    branches: ["main"]
  paths:
    # Just run on main branch if "native" path changed.
    - "lib/**"
    - "mix.exs"
    # Also run if this file changes.
    # - ".github/workflows/rust.yml"
    - ".github/workflows/**"
  pull_request:
    branches: ["main"]

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always
  TOOLCHAIN: nightly
  CARGO_CACHE_PATH: |
    ./native/iroh_ex/target/
    ~/.cargo/.crates.toml
    ~/.cargo/.crates2.json
    ~/.cargo/bin/
    ~/.cargo/registry/index/
    ~/.cargo/registry/cache/
    ~/.cargo/git/db/

jobs:
  
  build:
    if: false
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, macos-latest]
    name: Build iroh_ex on ${{ matrix.platform }}
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust Nightly
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.TOOLCHAIN }}
          components: rust-src, llvm-tools-preview

      - name: Build iroh_ex
        run: |
          cd native/iroh_ex
          cargo build --release
          cd ../..
          tar -czf iroh_ex-${{ matrix.platform }}.tar.gz -C native/iroh_ex target/release

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: iroh_ex-${{ matrix.platform }}
          path: iroh_ex-${{ matrix.platform }}.tar.gz

  test:
    if: false
    needs: build
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, macos-latest]
        test-config: 
          - { node_cnt: 5, msg_cnt: 1_000 }
          - { node_cnt: 5, msg_cnt: 10_000 }
          - { node_cnt: 5, msg_cnt: 100_000 }
          - { node_cnt: 10, msg_cnt: 100_000 }
          - { node_cnt: 50, msg_cnt: 100_000 }
          - { node_cnt: 100, msg_cnt: 500_000, rand_msg_delay: 500 }
          - { node_cnt: 200, msg_cnt: 500_000, rand_msg_delay: 1000 }
    name: Test ${{ matrix.test-config.node_cnt }} ${{ matrix.test-config.msg_cnt }} on ${{ matrix.platform }}
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      - name: Download iroh_ex Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: iroh_ex-${{ matrix.platform }}

      - name: Extract iroh_ex to deps/
        run: |
          mkdir -p deps/iroh_ex/target/release
          tar -xzf iroh_ex-${{ matrix.platform }}.tar.gz -C deps/iroh_ex/target/release
          LIB_NAME=`find deps/iroh_ex/target/release -name "libiroh_ex.a" -o -name "libiroh_ex.so" -o -name "libiroh_ex.dylib" | head -n 1`
          mkdir -p priv/native/
          cp $LIB_NAME priv/native/

      - name: Cache ASDF and Toolchains
        uses: actions/cache@v4
        id: asdf-cache
        with:
          path: ~/.asdf
          key: asdf-cache-${{ runner.os }}-${{ hashFiles('.tool-versions') }}
          restore-keys: |
            asdf-cache-${{ runner.os }}-

      - name: Setup asdf env
        id: asdf-setup
        run: |
          echo PATH="$HOME/.asdf/shims:$HOME/.asdf/bin:$PATH" >> "$GITHUB_ENV"

      - name: Setup asdf
        uses: asdf-vm/actions/setup@master

      - name: Install CD tools from .tool-versions
        continue-on-error: true
        if: steps.asdf-cache.outputs.cache-hit != 'true'
        uses: asdf-vm/actions/install@master

      - name: Test asdf tools
        id: asdf-test
        run: |
          erl -version
          elixir --version
          mix --version

      - name: Install dependencies
        run: |
          mix deps.get
          mix deps.compile

      - name: Run Tests
        run: |
          RUST_LOG="iroh=info,iroh_ex=debug" \
          NODE_CNT=${{ matrix.test-config.node_cnt }} \
          MSG_CNT=${{ matrix.test-config.msg_cnt }} \
          RAND_MSG_DELAY=${{ matrix.test-config.rand_msg_delay }} \
          MIX_ENV=dev \
          mix test 2>&1 | tee mix_test_output.log

      - name: Upload Test Artifact
        uses: actions/upload-artifact@v4
        with:
          name: iroh_ex-${{ matrix.platform }}-tests-${{ matrix.test-config.node_cnt }}-${{ matrix.test-config.msg_cnt }}-${{ matrix.test-config.rand_msg_delay }}
          path: |
            *.log
            *.mmd
            *.txt
